# Generated by Django 3.2.9 on 2021-12-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_extra_fields_defined_in_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': {('cancel_order', 'Can cancel order')}},
        ),
    ]
